### ISSUE TITLE
[Bazel CI] Error: 'struct' value has no field or method 'to_json'



### ISSUE THREAD

**Issue by sgowroji** [bazel-contrib/rules_jvm_external#1080]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3740#018e5f2f-8012-4d03-a482-1b81bc57c860

 Platform: Ubuntu

 Logs: 
```
ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/f4869dab816286661a26d778dac20444/external/io_bazel_rules_scala/third_party/dependency_analyzer/src/main/BUILD:3:9: in scala_library_for_plugin_bootstrapping rule @@io_bazel_rules_scala//third_party/dependency_analyzer/src/main:scala_version:
Traceback (most recent call last):
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/f4869dab816286661a26d778dac20444/external/io_bazel_rules_scala/scala/private/rules/scala_library.bzl", line 142, column 22, in _scala_library_for_plugin_bootstrapping_impl
		return run_phases(
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/f4869dab816286661a26d778dac20444/external/io_bazel_rules_scala/scala/private/phases/api.bzl", line 45, column 23, in run_phases
		return _run_phases(ctx, builtin_customizable_phases, target = None)
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/f4869dab816286661a26d778dac20444/external/io_bazel_rules_scala/scala/private/phases/api.bzl", line 77, column 32, in _run_phases
		new_provider = function(ctx, current_provider)
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/f4869dab816286661a26d778dac20444/external/io_bazel_rules_scala/scala/private/phases/phase_default_info.bzl", line 20, column 23, in phase_default_info
		phase_names.remove("to_json")
Error in remove: item "to_json" not found in list
``` 
 Culprit: https://github.com/bazelbuild/bazel/commit/8f18d362c852377740cb032b02c42d78b9a44ad0

 Steps:
  ``` 
 git clone https://github.com/bazelbuild/rules_jvm_external
git reset 7ba59df6afa05c9e2d9356e1adb99f016a7c01eb  --hard
export USE_BAZEL_VERSION=b100e4f1631da2d7c78621c040e88b7644985cd8
bazel build //... 
 ``` 
 CC Greenteam @salmasamy

**Comment by sgowroji** [comment]
CC [@c-mita](https://github.com/c-mita)

**Comment by sgowroji** [comment]
CC @[shs96c](https://github.com/shs96c) @jin Could you please take a look on the above failures.  Thanks!
