### ISSUE TITLE
Contributors only: CI build broken due to "Error in aar_import: Couldn't auto load 'aar_import' from '@rules_android//rules:rules.bzl'."

### ISSUE THREAD

**Issue by vorburger** [bazel-contrib/rules_jvm_external#1304]
While raising #1303 I noticed that the CI failed with the following error, which is unrelated to my PR, and perhaps should be fixed, to make it less confusing for contributors:

```
tests/bazel_run_tests.sh
WARNING: For repository 'bazel_features', the root module requires module version bazel_features@1.17.0, but got bazel_features@1.21.0 in the resolved dependency graph. Please update the version in your MODULE.bazel or set --check_direct_dependencies=off
WARNING: For repository 'rules_java', the root module requires module version rules_java@7.12.2, but got rules_java@8.6.1 in the resolved dependency graph. Please update the version in your MODULE.bazel or set --check_direct_dependencies=off
WARNING: For repository 'io_bazel_stardoc', the root module requires module version stardoc@0.7.0, but got stardoc@0.7.1 in the resolved dependency graph. Please update the version in your MODULE.bazel or set --check_direct_dependencies=off
WARNING: For repository 'protobuf', the root module requires module version protobuf@27.2, but got protobuf@29.0 in the resolved dependency graph. Please update the version in your MODULE.bazel or set --check_direct_dependencies=off
DEBUG: /workdir/private/extensions/maven.bzl:351:18: The maven repository 'maven' has contributions from multiple bzlmod modules, and will be resolved together: ["protobuf", "rules_jvm_external"]
DEBUG: /workdir/private/extensions/maven.bzl:351:18: The maven repository 'multiple_lock_files' has contributions from multiple bzlmod modules, and will be resolved together: ["bzlmod_lock_files", "rules_jvm_external"]
WARNING: Couldn't auto load rules or symbols, because no dependency on module/repository 'rules_android' found. This will result in a failure if there's a reference to those rules or symbols.
ERROR: Traceback (most recent call last):
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/+maven+regression_testing_coursier/BUILD", line 48, column 11, in <toplevel>
		aar_import(
Error in aar_import: Couldn't auto load 'aar_import' from '@rules_android//rules:rules.bzl'.
WARNING: Target pattern parsing failed.
ERROR: Skipping '@regression_testing_coursier//:pin': no such target '@@+maven+regression_testing_coursier//:pin': target 'pin' not declared in package '' defined by /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/+maven+regression_testing_coursier/BUILD
ERROR: no such target '@@+maven+regression_testing_coursier//:pin': target 'pin' not declared in package '' defined by /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/+maven+regression_testing_coursier/BUILD
INFO: Elapsed time: 3.967s
INFO: 0 processes.
ERROR: Build did NOT complete successfully
ERROR: Build failed. Not running target
Traceback (most recent call last):
  File "/workdir/bazelci.py", line 4496, in <module>
    sys.exit(main())
  File "/workdir/bazelci.py", line 4464, in main
    execute_commands(
  File "/workdir/bazelci.py", line 1212, in execute_commands
    PrepareRepoInCwd(True, initial_setup=True)
  File "/workdir/bazelci.py", line 1210, in PrepareRepoInCwd
    execute_shell_commands(task_config.get("shell_commands", None), print_cmd_groups)
  File "/workdir/bazelci.py", line 1734, in execute_shell_commands
    execute_command([shell_command], shell=True)
  File "/workdir/bazelci.py", line 2645, in execute_command
    return subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['set -e\nbazel run @regression_testing_coursier//:pin\nbazel run @regression_testing_maven//:pin\nbazel run @maven_install_in_custom_location//:pin\ntests/bazel_run_tests.sh']' returned non-zero exit status 1.
🚨 Error: The command exited with status 1
```

**Comment by vorburger** [comment]
I'm closing this ancient issue (from me), given that CI on this project is green today.
